[project]
name = "inngest"
version = "0.1.0"
description = "Python SDK for Inngest"
readme = "README.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Flask",
    "Framework :: Tornado",
    "Intended Audience :: Developers",
]
requires-python = ">=3.10"

dependencies = ["pydantic>=2", "requests>=2.27.0"]

[project.optional-dependencies]
extra = [
    "Flask==3.0.0",
    "black==23.10.0",
    "isort==5.12.0",
    "mypy==1.6.1",
    "pylint==3.0.1",
    "pytest==7.4.2",
    "pytest-xdist[psutil]==3.3.1",
    "python-json-logger==2.0.7",
    "toml==0.10.2",
    "tornado==6.3.3",
    "types-requests==2.27.31",
    "types-toml==0.10.8.7",
    "types-tornado==5.1.1",
]

[project.urls]
"Homepage" = "https://github.com/inngest/inngest-py"
"Bug Tracker" = "https://github.com/inngest/inngest-py/issues"

[tool.black]
line-length = 80

[tool.isort]
line_length = 80
profile = "black"

[tool.mypy]
disallow_untyped_defs = true
incremental = false
strict = true

[tool.pylint.'MESSAGES CONTROL']
disable = [
    'broad-exception-caught',
    'broad-exception-raised',
    'duplicate-code',
    'fixme',
    'invalid-envvar-value',
    'line-too-long',
    'missing-docstring',
    'too-few-public-methods',
    'too-many-arguments',
    'unused-argument',
]
