[project]
name = "inngest"
version = "0.1.2"
description = "Python SDK for Inngest"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: FastAPI",
    "Framework :: Flask",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.10"

dependencies = ["httpx>=0.24.0", "pydantic>=2.1.1"]

[project.optional-dependencies]
extra = [
    "Flask==3.0.0",
    "black==23.10.0",
    "build==1.0.3",
    "fastapi==0.104.0",
    "isort==5.12.0",
    "mypy==1.6.1",
    "pylint==3.0.1",
    "pytest==7.4.2",
    "pytest-xdist[psutil]==3.3.1",
    "python-json-logger==2.0.7",
    "toml==0.10.2",
    "tornado==6.3.3",
    "types-toml==0.10.8.7",
    "types-tornado==5.1.1",
    "uvicorn==0.23.2",
]

[project.urls]
"Homepage" = "https://github.com/inngest/inngest-py"
"Bug Tracker" = "https://github.com/inngest/inngest-py/issues"

[tool.black]
line-length = 80

[tool.isort]
line_length = 80
profile = "black"

[tool.mypy]
disallow_untyped_defs = true
incremental = false
strict = true

[tool.pylint.'MESSAGES CONTROL']
disable = [
    'broad-exception-caught',
    'broad-exception-raised',
    'duplicate-code',
    'fixme',
    'invalid-envvar-value',
    'line-too-long',
    'missing-docstring',
    'too-few-public-methods',
    'too-many-arguments',
    'too-many-instance-attributes',
    'too-many-return-statements',
    'unused-argument',
]

[tool.ruff]
exclude = [".venv"]
line-length = 80

# https://docs.astral.sh/ruff/rules
extend-select = ['Q', 'RUF100', 'C90', 'UP', 'I', 'D', 'T']
extend-ignore = ['D202', 'D203', 'D205', 'D212']

[tool.ruff.extend-per-file-ignores]
"examples/**/*.py" = ['D', 'T20']
"tests/**/*.py" = ['C901', 'D', 'T20']

[tool.ruff.lint]
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
